I18n
tam-03/books_app pull request #1
Opened 2020-09-17 09:32 UTC by tam-03

Railsのプラクティス、i18nの課題です。

2020-09-21 07:34 UTC, betachelsea commented
せっかくなのでgitのcommit積み直しをやってみましょうか！
覚えておくと色々と便利です 👍 
参考: (ブランチのコミットを1から積み直す) https://bottoms-programming.com/archives/git-command-one-year.html#toc6

参考にしつつ手順をご説明します。**一旦全部説明を読んでいただいて、何が起こるかを把握されてからお手元でやってみると良いかと思います！**

1. まず i18n ブランチを選んでいる状態にします。
```
$ git checkout i18n   ... i18nブランチを選択します
$ git branch  ... いま選んでいるブランチを念の為確認します
```
<img width="717" alt="スクリーンショット 2020-09-21 16 06 06" src="https://user-images.githubusercontent.com/2603449/93740636-e093e600-fc25-11ea-8e6f-2bd77ee5257d.png">


ついでに今のcommit logがどうなっているか確認します。ずらっとコミットが積まれていることが分かります。
※シンプルに見たいので1行1commitで表示しています。
```
$ git log --oneline
```
<img width="717" alt="スクリーンショット 2020-09-21 16 11 55" src="https://user-images.githubusercontent.com/2603449/93740694-f7d2d380-fc25-11ea-8b34-de60a05b480a.png">


2. コミットをmasterの位置まで取り消しをします。
masterからi18nのブランチを作って以降に編集したファイルがすべてずらっとでてきます。
```
$ git reset --mixed master
```
<img width="717" alt="スクリーンショット 2020-09-21 16 12 43" src="https://user-images.githubusercontent.com/2603449/93740798-2c468f80-fc26-11ea-9f47-8332971cc8ad.png">


git status で状態を確認すると、改めて対象ファイル群を確認できます。
```
$ git status
```
<img width="717" alt="スクリーンショット 2020-09-21 16 18 21" src="https://user-images.githubusercontent.com/2603449/93740752-15a03880-fc26-11ea-98b8-1cf20f0fc8dc.png">


git log を見ると、初回commit ~ master の分のログしかなく、うまく取り消しできていることがわかります。

```
$ git log --oneline
```

<img width="717" alt="スクリーンショット 2020-09-21 16 15 58" src="https://user-images.githubusercontent.com/2603449/93740762-1933bf80-fc26-11ea-9000-03a4177a9c23.png">


3. コミットを詰み直します。
一旦ひとまとめにしたいものを add して
```
$ git add #{ファイル}
```
<img width="892" alt="スクリーンショット 2020-09-21 16 22 49" src="https://user-images.githubusercontent.com/2603449/93741844-176afb80-fc28-11ea-8c30-bee6326f0e5a.png">



add したら commit します。
```
$ git commit -m 'delete unuse files'
```
<img width="892" alt="スクリーンショット 2020-09-21 16 26 18" src="https://user-images.githubusercontent.com/2603449/93741799-06ba8580-fc28-11ea-9197-44ccac43f859.png">


このひとまとめにしたい分をadd -> commit を積み直しぶんだけ( git status で変更されたファイルが表示されなくなるまで ) 繰り返します。

4. 再push
Githubにはすでにi18nブランチがpushされている状態なので、強制pushをおこないます。
強制pushはかなり強力なコマンドなので要注意なのですが（例えばmasterブランチに対して空っぽの状態が強制pushされると、それまでにあった成果物としての内容が全部消えてしまいます）、PullRequestで積みあがったコミットをどうにかしたいケースでは実施されることもあるかと思います。そのあたりは開発しているチームのポリシーとかで決まってきそうなので、**「すごく気をつけて使う必要のあるコマンドである」** ということだけ念頭においてください！！

```
$ git push --force-with-lease
```

(これはやっちゃうと上書きされちゃうので自分からはスクショはありません! 🙇  )


分からないところがあればお気軽にご質問ください！

2020-09-21 07:49 UTC, betachelsea requested changes
gitの他、一旦さっと気になったところについてコメントさせていただきました！

2020-09-21 07:49 UTC, betachelsea commented on README.md
> +# i18nでアプリを多言語化する課題のブランチ
README はこのリポジトリに関する情報を記入しておくファイルなので、ブランチ毎に変更していたらgitのコンクリフトが発生してしまって大変そうです 💦 
もし積み直しされる際にREADME.mdの変更いらないや、というときで、 `$ git status` で Changes not staged for commit の一覧に表示され続けて困った場合は、次のようにすることで変更を取り消すことができます。
```
$ git restore README.md
```
`$ git restore .` としてしまうと全てのファイルの変更が消えてしまうのでこれも取り扱いに十分注意してください！

参考: https://iucstscui.hatenablog.com/entry/2019/11/04/231212

2020-09-21 07:49 UTC, betachelsea commented on app/views/books/edit.html.erb
> +<h1><%= t 'books.edit.title' %></h1>
ここのキーについて、 `books.edit.title` って書くの長いな〜と思う場合は、 `.title` とすることもできます。
やり方については下記記事を参照してください！

lazy-lookupについて(4.1.4 探索の「遅延」)
https://railsguides.jp/i18n.html#%E6%8E%A2%E7%B4%A2%E3%81%AE%E3%80%8C%E9%81%85%E5%BB%B6%E3%80%8D%EF%BC%88lazy-lookup%EF%BC%89

2020-09-21 07:49 UTC, betachelsea commented on app/views/books/index.html.erb
> +        <td><%= link_to t('books.index.destroy'), book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
ここの `Are you sure?` もi18nを適用してください。

2020-09-21 07:49 UTC, betachelsea commented on app/views/books/_form.html.erb
> +    <%= form.label t('books.create.title') %>
label は `ja.activerecord.attributes.book.title` のようにキーを設定しておくことで、 `<%= form.label :title %>` の表記でもi18nを適用してくれます！

参考: https://qiita.com/kinokosan/items/ab6c2cd60496dcb2bac0

2020-09-22 06:50 UTC, tam-03 commented on app/views/books/_form.html.erb
> +    <%= form.label t('books.create.title') %>
適用出来ました！🙇🏻‍♂️

2020-09-22 06:50 UTC, tam-03 commented on app/views/books/index.html.erb
> +        <td><%= link_to t('books.index.destroy'), book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
こちらも適用出来ました！

2020-09-22 06:50 UTC, tam-03 commented on app/views/books/edit.html.erb
> +<h1><%= t 'books.edit.title' %></h1>
変更出来ました！

2020-09-22 06:50 UTC, tam-03 commented on README.md
> +# i18nでアプリを多言語化する課題のブランチ
確かにコンフリクトが発生していました💦
ご指摘ありがとうございます！🙇🏻‍♂️

2020-09-22 06:53 UTC, tam-03 commented
commit の積み直し、とても参考になりました！ご丁寧な解説をありがとうございます！🙇🏻‍♂️

2020-09-23 00:48 UTC, betachelsea requested changes
commit がうまく積み直しされたみたいですね！ ありがとうございます。
また、i18n自体もいい感じに修正されたと思います :+1: 

今回はRailsアプリにおいてcommitすべきもの・すべきでないものについて再整理していきたいと思います。
改めて自分の開発環境でこのアプリを動かそうと思ったところ、色々必要なものが足りておらず、動かないということに気付きました 😭   前回指摘しそこねており、すみません...！

gitを使ってリポジトリを共有する一番の目的として、複数人が開発をするためというものがあると思います。
このとき、Rails new した人が最初にコミットしてGitHubにアップしたものを、他の開発者がgit clone してきて、そして動かせる環境にできる必要があります。
なので、動かすために必要なファイルはコミットに含んでおく必要があります。

主に必要なファイルとしては、次のようなものがあります。
・app/ 以下のファイル
・db/ 以下のmigrationファイルなど ( *sqlite3 のファイルは不要 )
・config/ 以下の設定ファイル ( *重要なシステムキーなどは環境変数を利用するなどの方法でコミットしないようにする )


一度、お手元にて今使っている `books_app` フォルダと別に空のフォルダを作成し、
そこでこのPullRequestの状態を持ってきて、`rails server` でRailsが動く状態を目指してみて欲しいです！

```sh
# books_app_clone というフォルダを作成
$ mkdir books_app_clone
$ cd books_app_clone

# このリポジトリをcloneする
$ git clone git@github.com:tam-03/books_app.git
$ cd books_app

# i18nブランチをもってくる
$ git checkout -b i18n origin/i18n

# おそらくGemfileが無いのでbundle install ができない?
$ bundle install
Could not locate Gemfile
```

おまけ: `.gitignore` の雛形ですが下記が結構参照されているかなと思います。
https://github.com/github/gitignore/blob/master/Rails.gitignore

2020-09-23 00:48 UTC, betachelsea commented on config/locales/ja.yml
> +      h1_html: '本の一覧'
キー名についてだけ... `h1_html` という表現だと、次のような問題がありそうです。
- html を含む内容と感じる (例、 `<h1>本の一覧</h1>` という値が入っているのでは? と誤解される可能性が高い)
- もし同じ表現を使いまわしたくなったとき、h1 以外の箇所では使うことをためらってしまうキーになっている

htmlという表記を使わない、またタグの英単語を用いない形で表現できないか再考をお願いします！ 🙏

2020-09-23 00:54 UTC, betachelsea commented
すみません、おまけでもう1点。
PullRequestのタイトルですが、「i18n」のみですとどうしたのかという表現が抜けていて、万が一ですが受け取り手によって
 「i18n( を、とりやめた...? )」
「i18n（を、変更した...?)」
と様々な解釈が可能な表現になってしまっているなと思いました。（もちろん、中身を見れば新規に適用したというのはわかるのですが！）

以降さまざまなシーンで、解釈違いによる悲しいすれ違いを防ぐために、できるだけ言葉を尽くして意図を伝えようとする癖をつけていただくのが良いかと思っています。
タイトルを改めてつけなおしてみて欲しいです！よろしくお願いします 👍

2020-09-23 09:19 UTC, tam-03 commented
ご指摘ありがとうございます！

分からなくて、お聞きしたい事があるのですが、「PullRequestの状態を持ってきて、`rails server` でRailsが動く状態」にならずに困っています。。

現状の手順だと、

`bundle install`

`rails s`

`yarn install`

`bundle exec rake db:migrate`

この手順でないとRailsアプリが動作しません。。

---

※`.gitignore`の設定は、最初から雛形を使わせて頂いていたのですが、自分でいくつか書き足していました💦

現状は`rubocop.yml`以外は雛形のデフォルトです。


## 修正した流れ

必要なファイルがpush出来ていなかった件なのですが、確かにGemfileが無かったので、`bundle install`出来ませんでした💦

そこで、`.gitignore`からGemfileを外し、

`app/`

`db/`

`config/`以下も外し、

`bundle install`をした所、実行出来たのですが、

`rails s`の時にエラーが出ました。

### エラー1: 「node_modules」がインストールされてない

```bash
$ rails s

error Couldn't find an integrity file
error Found 1 errors.                                                                                                                     


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).
```
こんな感じのエラーだったのですが、**`node_modules` がインストールされてないのが原因**だそうで、

参考: [Rails6 開発時につまづきそうな webpacker, yarn 関係のエラーと解決方法](https://qiita.com/NaokiIshimura/items/8203f74f8dfd5f6b87a0#%EF%B8%8F-node_modules-%E3%81%8C%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%95%E3%82%8C%E3%81%A6%E3%81%AA%E3%81%84)

参考を基に、`yarn install`で解決したのですが、`rails s`した後に、`http://localhost:3000/books`にアクセスすると、

### エラー2: 「Migration」を保留している

こんなエラーが、(画像は引用です)
https://i.gyazo.com/a148211933aa14a37a9f19836d1e8d5a.png

エラー内容
```
Migrations are pending. To resolve this issue, run: rails db:migrate RAILS_ENV=development
```
参考: [ActiveRecord::PendingMigrationError と言われた時の解決方法](https://qiita.com/pugiemonn/items/718b7360028286c5b626)

**Migrationを保留しているというエラー**だそうで、`bundle exec rake db:migrate`で解決し、表示してやっと動く状態になりました。

---

これでは、「PullRequestの状態を持ってきて、`rails server` でRailsが動く状態」では無いので完了していないのですが、なぜ、

`$ git clone`

`$ bundle install`

`$ rails s`

で動かないのかが分かりません😭

## 質問

そこで質問させて頂きたいのですが、

このbooksアプリの場合、`yarn install`,`bundle exec rake db:migrate`は、`README.md`に使い方を書く様な、**必要な手順**なのでしょうか？

長々とすみませんが、お手隙の際にご返信頂けると助かります！🙇🏻‍♂️

よろしくお願い致します！

2020-09-23 09:19 UTC, tam-03 commented
PullRequestのタイトル、曖昧なままで決めてしまいました💦
ご指摘ありがとうございます！
変更しました！

2020-09-23 09:20 UTC, tam-03 commented on config/locales/ja.yml
> +      h1_html: '本の一覧'
確かにそうでした。。ご指摘ありがとうございます！
`_html`になっている部分を修正しました。

2020-09-23 09:43 UTC, tam-03 commented
すみません！もう一つ質問があるのですが、`config/`以下の設定ファイルで、環境変数にして公開を避けるべきファイルはどの様なファイルなのでしょう？

「外に公開してはいけない、秘密の情報」などを検索するワードが分からなくて困っております😭

駒形さんのこの記事も確認したのですが、よく分かりませんでした💦
https://docs.komagata.org/5676#secret_data

dbのユーザー・パスワード等、ユーザー認証(?)などの際に使うファイルやコードなのでしょうか？🤔

2020-09-23 15:05 UTC, betachelsea commented on config/locales/ja.yml
> +      h1_html: '本の一覧'
こちら日報のほうにも書かせていただきましたが、誤解という意味だけでなくちゃんとRails側が `_html` というキーにするとHTMLエスケープさせないという特別な機能をもっていました！確認不足ですみません :bow: 
[https://railsguides.jp/i18n.html#4.4安全なHTML変換](https://railsguides.jp/i18n.html#%E5%AE%89%E5%85%A8%E3%81%AAhtml%E5%A4%89%E6%8F%9B)

もし使う場合は、適切なタイミングで使っていけるといいですね 👍

2020-09-23 16:03 UTC, betachelsea requested changes
### Railsアプリ動作手順

すみません、これは自分の説明が不足していたようです！
ご説明いただいたとおり、次の手順が正しいと思います。

```
$ git clone
$ bundle install
$ yarn install
$ bundle exec rake db:migrate
$ rails s
```

書くのを忘れてしまった理由としては、自分は普段古いリポジトリを仕事として運用しているのですが、migration および yarn が必要になる変更をあまり普段対応しないためスポンと抜けておりました...大変申し訳ないです！

> このbooksアプリの場合、yarn install,bundle exec rake db:migrateは、README.mdに使い方を書く様な、必要な手順なのでしょうか？

はい、動かすために必要ですので、README.md に書いてあると後続の開発者のためになって良いと思います :+1:
プロジェクトによっては、今回tam-03さんが自己解決していただいたように、エラー時にはちゃんとこのコマンドを叩いてくださいという案内が出るので、それを見ればOKでしょうという解釈をして書いていないケースもあるかもしれません。



### config/以下の設定ファイルで、環境変数にして公開を避けるべきファイルはどの様なファイルなのでしょう？

「外部に漏れてしまうとセキュリティ的に問題がある」文字列は基本的にコミットしません。
特に、現在このリポジトリはpublicリポジトリ(誰でも閲覧できる状態)なので、特に注意する必要があると思います。

公開を避ける方法としては、「環境変数にする」以外にも「ファイル自体を.gitignoreに設定してコミットしない」ケースがあります。`.gitignore` に書かれている次の2ファイルが「ファイル自体をコミットしない」ケースの主な例になるかなと思います。

```
# TODO Comment out this rule if you are OK with secrets being uploaded to the repo
config/initializers/secret_token.rb
config/master.key
```

これのTODOコメントは、「privateリポジトリとして組織内でしか公開してないとかなら、入れるという判断もありですよ」という意味合いにも取れるように感じます。あとはGitHubさんのセキュリティをどこまで信じるかという話になりそうです :eyes:  

ここの表記のうち、secret_token.rb は 古いRails4系で利用されていたものなので、実はもう気にしなくて良いかなと思います。
`config/master.key` は、現在のRails(今は最新6.0ですね)で利用される重要な鍵です。`rails credentials:edit` コマンドは `config/master.key` を暗号化の鍵として秘密情報の編集ができる機能です。編集された秘密情報は `config/credentials.yml.enc` に保存されますが、このファイルは  `config/master.key` を用いて復号しない場合、ぱっと見ても変な文字列が並んでいるだけでよくわからない(暗号化されている)状態になっています。 適切な `config/master.key` を配置することで、Railsアプリからはまともな文字列として読めるようになります。
適当な文字列は万が一漏れても基本的には問題ないと考えてコミットし、代わりに鍵として`config/master.key` を厳重に守るためにコミットに含みません。鍵と暗号文字がセットでコミットされていたら、どっちもバレたらすぐに復号されてしまうのでNGです。

詳しくはこちらをご覧ください！
[https://railsguides.jp/security.html#10.1 独自のcredential](https://railsguides.jp/security.html#%E7%8B%AC%E8%87%AA%E3%81%AEcredential)

一応Railsガイドにも次のように書かれていますね。

> マスターキーは安全な場所に保管してください。マスターキーをコミットに含めてはいけません。


さらに「一体何を暗号として管理すれば良いのか」ですが、ご指摘の通りDBのユーザー名とパスワードとか、あと関連するサービスのログイン情報などです。特に大事故に繋がる話が時々でてくるのはAWS(Amazon Web Service) です。AWSでサーバを立てるとお金が当然かかるのですが、今時はサーバを使ってできるお金儲けとしてビットコインの採掘とかがあったりとか、他にもサーバを他人のお金で作って無限に使いたいという悪い人たちからのニーズはたくさんあります。特にGithubのpublicリポジトリにうっかりAWSのログイン情報をわかりやすく置いてしまうとシュッと抜かれて使われてしまうそうです。本当にありうる怖い話としてぜひ事前に把握しておいてください！
[GitHub に AWS キーペアを上げると抜かれるってほんと？？？試してみよー！ - Qiita](https://qiita.com/saitotak/items/813ac6c2057ac64d5fef)

2020-09-24 04:42 UTC, tam-03 commented
質問のご回答をありがとうございます！
必要なのかどうかも分からない状態でしたがスッキリ解消しました！

> migration および yarn が必要になる変更をあまり普段対応しないため

逆に言えば必要でないケースもあるんですね！

> エラー時にはちゃんとこのコマンドを叩いてくださいという案内が出るので、それを見ればOKでしょうという解釈をして書いていないケースもあるかもしれません。

確かにコマンドを叩くだけだったので書かなくても良いとなりそうですね！

---

秘密の情報の公開を避ける方法についても大変勉強になります！

初心者の考えた事としては、

「秘密の情報は`config/`以下のどこかのファイルに点在していて、それを環境変数にして公開を避ける」

だと思っていたので、

- そもそも秘密の情報とは何か
- どこにどんな秘密の情報があるのか
- 環境変数にするには？
- これで安全なのかどうか

以上を頭でループしていました。

多分点在している場合もあって、`gem 'dotenv-rails'`このGemを使ったり、雛形の`.gitignore`に

```
# dotenv, dotenv-rails
# TODO Comment out these rules if environment variables can be committed
.env
.env.*
```

`.env`ファイルを追跡しない記述があるんですよね！


気をつけなければいけない事が、`config/master.key`を安全に保管する事で、秘密の情報は基本的に`config/credentials.yml.enc`ここに記載して暗号化。

コミットはOK。という事ですよね！

---

AWSの場合の例怖いですね。。`awslabs/git-secrets`
これを覚えておきます！

2020-09-24 04:42 UTC, tam-03 commented on app/views/books/edit.html.erb
> +<h1><%= t '.title' %></h1>
ご指摘ありがとうございます！

`t('.title')`に統一しました！

2020-09-24 04:43 UTC, tam-03 commented on .gitignore
> +/.rubocop.yml
> チームで進めていく場合はルール共有のためにリポジトリに含めておいて管理するのがよくあるケース

そうなんですね！ありがとうございます！
`.rubocop.yml`をリポジトリに追加しました！

2020-09-25 00:02 UTC, betachelsea requested changes
細かいところですが追加コメントさせていただきました！ 🙏 

> 秘密の情報
> 多分点在している場合もあって
> config/master.keyを安全に保管する事で、秘密の情報は基本的にconfig/credentials.yml.encここに記載して暗号化

書いていただいている解釈でだいたいOKと思います！ 🙆 
どこに何を書くかというのは各プロジェクトの都合などももちろん出てくるので、点在していたり、統一されていたり、様々かなと思います。とりあえず重要なのは **平文 ( 暗号化されていない) 状態でコミットしない**、 **暗号化されている場合は鍵(今回の場合master.key)をコミットしない** ...ということかなと思います！
今後さらにRailsや各種gemがアップデートされていくなかで、ベストなやり方というのは変わってくるのかなと思いますが、ぜひ引き続き注意してみてください〜 👀  

> awslabs/git-secrets

おお、これ知りませんでした！
自分も使ってみようと思います〜 👍

2020-09-25 03:00 UTC, tam-03 commented on app/views/books/index.html.erb
> +<h1><%= t '.books' %></h1>
すみません！見逃してました💦

2020-09-25 03:02 UTC, tam-03 commented on config/locales/ja.yml
> +      title:
削除して、これの下の、
title:
memo:
なども、activerecordのモデルで参照する記述に書き換えました！

2020-09-25 03:03 UTC, tam-03 commented on config/locales/ja.yml
> +      title: 'タイトル'
こちらに書き換えました！

2020-09-26 00:22 UTC, betachelsea approved these changes
修正ありがとうございます！レビューOKです 🎉

2020-10-01 02:52 UTC, merged