omniauthでgithub認証を実装しました。
tam-03/books_app pull request #4
Opened 2020-10-13 02:50 UTC by tam-03

railsのomniauthプラクティスの課題です。
ご確認をよろしくお願い致します。

2020-10-16 20:13 UTC, komagata requested changes

2020-10-16 20:13 UTC, komagata commented on .rubocop.yml
> +    - "config/rails.yml"
最終行に改行が無いようです。

2020-10-16 20:13 UTC, komagata commented on app/controllers/users/omniauth_callbacks_controller.rb
> +      @user = User.from_omniauth(request.env['omniauth.auth'].except('extra'))
> except('extra')

👍

2020-10-17 06:20 UTC, tam-03 commented on .rubocop.yml
> +    - "config/rails.yml"
すみません！改行を入れました！

2020-10-20 01:02 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-10-20 04:27 UTC, merged